# Generated by Django 3.0.5 on 2020-04-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_date',
            new_name='data_adicionada',
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
