# Generated by Django 3.0.5 on 2020-04-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200414_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='data_adicionada',
        ),
    ]
